### ISSUE TITLE
Questions about open source of ImageNet-LT-d

### ISSUE THREAD

**Issue by zuglerQ** [dvirsamuel/DRAGON#3]
Hi, 
I appreciate your work that introducing class descriptors into the long-tailed problem.  I would like to know is that possible to share the ImageNet-LT-d database so that we could compare the results with recent papers that were evaluated on ImageNet-LT.

**Comment by dvirsamuel** [comment]
Hi zuglerQ,
The ImageNet-LT-d dataset is based on Imagenet LT ([Liu et al](https://arxiv.org/abs/1603.00550) - which can be found [here](https://github.com/zhmiao/OpenLongTailRecognition-OLTR)) with class word embeddings as textual descriptors ([Changpinyo et al](https://arxiv.org/abs/1904.05160) - which can be found [here](https://www.dropbox.com/s/f9p3u6883xmt58k/ImageNet_w2v.zip?dl=0))
